development:
  adapter: postgresql
  encoding: unicode
  database: atom_development
  # pool: 5
  # connections: 20
  username: onuruyar
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: atom_test
  # pool: 5
  # connections: 20
  username: onuruyar
  password:
  host: localhost
  port: 5432

production:
  <% if db = URI.parse(ENV['DATABASE_URL']) rescue nil %>
  adapter: <%= db.scheme == "postgres" ? "postgresql" : db.scheme %>
  encoding: unicode
  database: <%= db.path[1..-1] %>
  # pool: 5
  # connections: 20
  username: <%= db.user %>
  password: <%= db.password %>
  host: <%= db.host %>
  port: <%= db.port %>
  <% end %>